#!/usr/bin/env node
/**
 * The documentary's voiceover timing system.
 *
 *   npm run video:timing
 *
 * Speaks every phrase of `video/src/films/doc-script.mjs`, measures it, and
 * writes the lengths to `doc-voice.timing.mjs`. The documentary's timeline
 * is laid out from those lengths plus each phrase's designed pause, so
 * re-voicing the film (a new take, a recorded narrator) re-times every shot
 * with it. Run it again whenever the script or the voice changes.
 */
process.env.VIDEO_FILM = 'doc';
const { writeFile } = await import('node:fs/promises');
const { join } = await import('node:path');
const { ROOT } = await import('./stage.mjs');
const { CACHE } = await import('./render.mjs');
const { lineAudio, TTS_VOICE } = await import('./audio/voice.mjs');
const { SCRIPT } = await import('../../video/src/films/doc-script.mjs');

const dir = join(CACHE, 'audio', 'vo');
const out = {};
let total = 0;
for (const p of SCRIPT) {
  const a = await lineAudio(p, dir, process.argv.includes('--force'));
  out[p.id] = Number(a.seconds.toFixed(3));
  total += p.pause + a.seconds;
  process.stdout.write(`  ${p.id} ${a.seconds.toFixed(2)}s ${a.source}\n`);
}
// Word-group onsets inside the habitat list (N09), from the silences in its
// recording, so the montage can cut exactly on each spoken word.
const { execFile } = await import('node:child_process');
const n09 = (await lineAudio(SCRIPT.find((p) => p.id === 'N09'), dir)).file;
const stderr = await new Promise((ok) => execFile('ffmpeg', ['-hide_banner', '-i', n09, '-af', 'silencedetect=noise=-38dB:d=0.12', '-f', 'null', '-'], (e, so, se) => ok(se)));
const onsets = [0, ...[...stderr.matchAll(/silence_end: ([0-9.]+)/g)].map((m) => Number(Number(m[1]).toFixed(3)))];
const WORDS = { N09: onsets };
console.log(`  N09 word onsets: ${onsets.join(', ')}`);

const file = join(ROOT, 'video/src/films/doc-voice.timing.mjs');
await writeFile(
  file,
  `// Generated by scripts/video/voice-timing.mjs from ${TTS_VOICE} — do not edit by hand.\n` +
    `// Measured length of each narration phrase, in seconds.\n` +
    `export const TIMING = ${JSON.stringify(out, null, 2)};\n\n` +
    `// Onsets of the spoken word groups inside a phrase, in seconds from its start.\n` +
    `export const WORDS = ${JSON.stringify(WORDS)};\n`,
);
console.log(`✓ ${SCRIPT.length} phrases, ${total.toFixed(1)} s of narration and pauses → ${file}`);
